server:
    port: 8888
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: greetings-in
          binder: rabbit1
        output:
          destination:greetings-out
          binder: rabbit1
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 15672
                username: guest
                password: guest